### ISSUE TITLE
better way to order countries

### ISSUE THREAD

**Issue by behrman** [dcl-docs/data-vis#9]
A preferable way to order countries by their last value:

    southern_africa_countries %>% 
      mutate(name = fct_reorder2(name, year, life_expectancy)) %>% 
      ggplot(aes(year, life_expectancy, color = name)) +
      geom_vline(xintercept = 1994, color = "blue") +
      geom_line() +
      geom_point() +
      theme(legend.justification = "top")

**Comment by skaltman** [comment]
I changed this in continuous-continuous and time-series!
